- hosts: all
  roles:
  - Stouts.deploy
  - Stouts.supervisor
  - Stouts.nginx
  - Stouts.python
  - Stouts.source
  - Stouts.wsgi
  tasks:
    - include: tasks/main.yml
  vars_files:
    - defaults/main.yml
    - vars/main.yml
