---

- name: django-manage | Run manage commands
  django_manage: >
    command={{item}}
    app_path={{django_app_dir}}
    settings={{django_settings_module}}
    virtualenv={{django_env_dir}}
  changed_when: False
  with_items: django_manage_list
  ignore_errors: django_ignore_errors
