---

- name: django-manage | Run manage commangs
  django_manage:
      command={{item}}
      app_path={{django_app_path}}
      settings={{django_settings_module}}
      virtualenv={{wsgi_virtualenv}}
  with_items: django_manage_list
  ignore_errors: yes
