---

- name: Sync database
  django_manage:
      app_path={{django_app_path}}
      command=syncdb
      settings={{django_settings_module}}
      virtualenv={{wsgi_virtualenv}}
  ignore_errors: "{{django_ignore_errors}}"

- name: Migrate database
  django_manage:
      app_path={{django_app_path}}
      command=migrate
      settings={{django_settings_module}}
      virtualenv={{wsgi_virtualenv}}
  ignore_errors: "{{django_ignore_errors}}"
